# content of: tox.ini , put in same dir as setup.py
[tox]
envlist = py311,py312

[testenv]
# install pytest in the virtualenv where commands will be executed
deps = pytest
  matplotlib

extras = test
commands =
    # NOTE: you can run any command line tool here - not just tests
    pytest {posargs}

[pytest]
# test_mount: requires Linux + sudo
# test_dockerutil: requires a running docker daemon
addopts = --ignore=yautil/tests/test_mount.py --ignore=yautil/tests/test_dockerutil.py
